export type Store = "both" | "xinyi" | "taichung";

export interface Promotion {
  id: string;
  brand: string;
  tagline?: string;
  audience?: string;
  title: string;
  description: string;
  period: string;
  store: Store;
  notes?: string;
  category: "fragrance" | "lifestyle" | "tea-wine" | "family";
  priceTier?: "u600" | "u1000" | "u1500" | "p3000";
  price?: string;
}

export const stores: Record<Store, string> = {
  both: "雙店同步 ・ 信義 + 市政",
  xinyi: "台北信義店",
  taichung: "台中市政店",
};

export const promotions: Promotion[] = [
  {
    id: "lasai",
    brand: "LASAI",
    tagline: "母親節限定",
    audience: "適合送給重視保養的她",
    title: "母親節限定身體套組",
    price: "NT$1,470",
    description:
      "母親節限定身體套組優惠價 NT$1,470，包含日常身體保養品項，適合送給重視香氣與肌膚照護的對象。",
    period: "4/1 — 5/10",
    store: "both",
    category: "fragrance",
    priceTier: "u1500",
  },
  {
    id: "santa-body",
    brand: "聖朵波緹",
    tagline: "折扣優惠",
    audience: "適合送給喜愛身體保養的她",
    title: "身體保養組合",
    price: "NT$599",
    description: "身體乳液＋沐浴膠組合，原價 NT$1,079，活動價 NT$599。",
    period: "4/1 — 6/30",
    store: "both",
    category: "fragrance",
    priceTier: "u600",
  },
  {
    id: "panier",
    brand: "Panier des Sens 潘提香頌",
    tagline: "全系列 75 折",
    audience: "適合送給喜愛香氛的她",
    title: "全系列 75 折",
    description: "潘提香頌全系列 75 折。精選法式香氛、身體清潔與護手保養。",
    period: "即期品除外",
    store: "both",
    category: "fragrance",
  },
  {
    id: "shinian-tea",
    brand: "蒔年一晌 茶 ／ 私咖啡",
    tagline: "茶咖禮盒 88 折",
    audience: "適合送給愛茶愛咖啡的她",
    title: "茶咖禮盒單件 88 折",
    description: "咖啡禮盒與蒔年一晌茶品系列，單件即享 88 折。",
    period: "4/1 — 5/31",
    store: "both",
    category: "tea-wine",
  },
  {
    id: "blackwhite",
    brand: "黑白小姐",
    tagline: "滿額贈",
    audience: "適合搭配其他禮品",
    title: "消費滿 NT$200 贈母親節卡片",
    description: "購買黑白小姐商品滿 NT$200，即贈母親節卡片乙張。",
    period: "數量有限・不累送",
    store: "both",
    category: "family",
  },
  {
    id: "betterology-gift",
    brand: "Betterology",
    tagline: "滿額贈",
    audience: "適合送給注重健康的她",
    title: "書店消費滿額贈體驗組",
    description: "於書店消費滿 NT$1,200，即贈 Betterology 體驗組乙份。贈品數量有限，送完為止。",
    period: "不累贈",
    store: "both",
    category: "lifestyle",
  },
  {
    id: "juecui",
    brand: "覺萃",
    tagline: "全品項 9 折",
    title: "全品項單品 9 折",
    description: "覺萃全品項單品 9 折。從居家清潔到身體照護，打造安心生活節奏。",
    period: "4/1 — 5/10",
    store: "both",
    category: "fragrance",
  },
  {
    id: "teapao",
    brand: "茶寶",
    tagline: "全品項 9 折",
    title: "全品項單品 9 折",
    description: "茶寶全品項單品 9 折。以茶籽保養，照顧日常肌膚與髮絲。",
    period: "4/1 — 5/10",
    store: "both",
    category: "fragrance",
  },
  {
    id: "betterology-95",
    brand: "Betterology",
    tagline: "單盒 95 折",
    title: "單盒 95 折",
    description: "Betterology 指定商品單盒 95 折。每日營養補給，從日常開始。",
    period: "4/1 — 5/10",
    store: "both",
    category: "lifestyle",
  },
  {
    id: "handiin",
    brand: "Handiin",
    tagline: "全品牌 88 折",
    title: "全品牌 88 折",
    description: "Handiin 全品牌商品 88 折。精選皮件與隨身配件，升級日常使用質感。",
    period: "4/1 — 5/10",
    store: "both",
    category: "lifestyle",
  },
  {
    id: "towels",
    brand: "今治 / Matsukan / MIYAZAKI TOWEL",
    tagline: "兩件 9 折",
    title: "日本生活選品兩件 9 折",
    description: "今治、Matsukan、MIYAZAKI TOWEL 品牌商品任選兩件 9 折。",
    period: "4/1 — 5/10",
    store: "both",
    category: "lifestyle",
  },
  {
    id: "mei-plum",
    brand: "覓梅酒",
    tagline: "組合優惠",
    title: "不能梅柚你組合",
    price: "NT$1,280",
    description: "⑤醺甜釀＋月神柚子酒組合優惠價 NT$1,280，原價 NT$1,800。",
    period: "4/1 — 5/10",
    store: "both",
    notes: "未滿 18 歲請勿飲酒",
    category: "tea-wine",
    priceTier: "u1500",
  },
  {
    id: "mecotio",
    brand: "美珂媞歐",
    tagline: "全品牌 7 折",
    title: "全品牌 7 折",
    description: "美珂媞歐香氛商品全品牌 7 折。挑選一款香氣，留給自己或送給重要的人。",
    period: "台北信義店限定",
    store: "xinyi",
    notes: "台北信義店限定",
    category: "fragrance",
  },
  {
    id: "j-scent",
    brand: "J-scent",
    tagline: "任選 2 件 85 折",
    title: "任選 2 件 85 折",
    description: "J-scent 香氛商品任選 2 件 85 折。把日本氣味收藏進日常。",
    period: "台北信義店限定",
    store: "xinyi",
    notes: "台北信義店限定",
    category: "fragrance",
  },
  {
    id: "ecoscential",
    brand: "EcoScential",
    tagline: "新品上市",
    title: "新品牌上市優惠",
    description: "環保香氛手工大豆蠟燭 NT$699，無火蘆葦擴香 NT$699，環境香氛噴霧 NT$499。",
    period: "4/1 — 6/30",
    store: "both",
    category: "fragrance",
    priceTier: "u1000",
  },
  {
    id: "yuyu",
    brand: "郁郁",
    tagline: "兩件 95 折",
    title: "任選 2 件 95 折",
    description: "郁郁品牌商品任選 2 件 95 折。精選日常生活香氣與保養選品。",
    period: "長期活動",
    store: "both",
    category: "fragrance",
  },
  {
    id: "santa-2",
    brand: "聖朵波緹",
    tagline: "1 件 8 折・2 件 7 折",
    title: "指定商品 1 件 8 折、2 件 7 折",
    description: "身體乳液、沐浴膠除外。消費滿 NT$800 再贈品牌擦手巾。",
    period: "4/24 — 6/30",
    store: "both",
    notes: "身體乳液、沐浴膠除外",
    category: "fragrance",
  },
  {
    id: "santa-perfume",
    brand: "聖朵波緹",
    tagline: "滿額贈",
    title: "購買香水贈香氛皂",
    description: "購買聖朵波緹香水或淡香精，即贈經典法式男士香氛皂乙份。",
    period: "贈品數量依現場為準",
    store: "both",
    notes: "贈完為止",
    category: "fragrance",
  },
  {
    id: "yoreh",
    brand: "Yoreh 悠若",
    tagline: "指定傘款 9 折",
    title: "母親節指定傘款 9 折",
    description: "指定晴雨傘單支 9 折。為日常通勤與送禮準備一把實用好傘。",
    period: "5/1 — 5/31",
    store: "both",
    category: "lifestyle",
  },
  {
    id: "kindbag",
    brand: "KIND BAG",
    tagline: "清倉 3 折",
    title: "清倉 3 折",
    description: "KIND BAG 品牌商品單件 3 折。環保袋款限量出清，6 月初下架還貨。",
    period: "6 月初下架",
    store: "both",
    notes: "限量出清",
    category: "lifestyle",
  },
  {
    id: "shinian-wine",
    brand: "蒔年一晌 酒品",
    tagline: "全品項 8 折",
    title: "酒品全品項 8 折",
    description: "蒔年一晌酒品全品項 8 折，精選歐洲酒款，適合節慶聚餐與送禮。",
    period: "4/17 — 5/11",
    store: "both",
    notes: "未滿 18 歲請勿飲酒",
    category: "tea-wine",
  },
  {
    id: "shinian-set",
    brand: "蒔年一晌",
    tagline: "組合優惠",
    title: "品味歐洲三國品酒組",
    price: "NT$5,200",
    description: "精選比利時、匈牙利、斯洛伐克三國酒款，組合優惠價 NT$5,200，原價 NT$7,097。",
    period: "4/17 — 5/11",
    store: "both",
    notes: "未滿 18 歲請勿飲酒",
    category: "tea-wine",
    priceTier: "p3000",
  },
  {
    id: "wattis",
    brand: "沃堤思世界茶莊園",
    tagline: "盒裝茶 3 件 NT$990",
    title: "盒裝茶任選 3 件 NT$990",
    description: "沃堤思世界茶莊園品牌盒裝茶，任選 3 件 NT$990。",
    period: "台中市政店活動",
    store: "taichung",
    notes: "台中市政店限定",
    category: "tea-wine",
  },
  {
    id: "magblox",
    brand: "MAGBLOX",
    tagline: "磁力片單盒 9 折",
    title: "磁力片單盒 9 折",
    description: "MAGBLOX 磁力片單盒 9 折。陪孩子用積木探索形狀、色彩與建構力。",
    period: "台中市政店限定",
    store: "taichung",
    notes: "台中市政店限定",
    category: "family",
  },
  {
    id: "sonny",
    brand: "SONNY ANGEL",
    tagline: "滿三件贈書籤",
    title: "購買滿三件贈限量書籤",
    description: "SONNY ANGEL 系列商品購物滿三件，即贈限量書籤乙枚。",
    period: "數量有限・不累贈",
    store: "both",
    category: "family",
  },
  {
    id: "ecoscential-spray",
    brand: "EcoScential",
    tagline: "新品",
    title: "環境香氛噴霧",
    price: "NT$499",
    description: "新品牌上市優惠，把日常空間留下乾淨氣味。",
    period: "4/1 — 6/30",
    store: "both",
    category: "fragrance",
    priceTier: "u600",
  },
  {
    id: "ecoscential-candle",
    brand: "EcoScential",
    tagline: "新品",
    title: "手工大豆蠟燭",
    price: "NT$699",
    description: "新品牌上市，溫和燃燒，留下柔和氣味。",
    period: "4/1 — 6/30",
    store: "both",
    category: "fragrance",
    priceTier: "u1000",
  },
  {
    id: "ecoscential-reed",
    brand: "EcoScential",
    tagline: "新品",
    title: "無火蘆葦擴香",
    price: "NT$699",
    description: "無火安心擴香，適合臥室與書房。",
    period: "4/1 — 6/30",
    store: "both",
    category: "fragrance",
    priceTier: "u1000",
  },
];

export const categoryMeta = {
  fragrance: {
    title: "香氛・保養",
    en: "FRAGRANCE & CARE",
    desc: "從香氛、身體清潔到護手保養，挑選能融入日常的照護選品。",
  },
  lifestyle: {
    title: "生活配件",
    en: "LIFESTYLE",
    desc: "從包款到晴雨傘，精選值得長期使用的日常好物。",
  },
  "tea-wine": {
    title: "茶・咖啡・酒",
    en: "TEA・COFFEE・WINE",
    desc: "精選茶品、咖啡與酒款禮盒，適合節慶餐桌、聚會分享與日常贈禮。",
  },
  family: {
    title: "親子選品",
    en: "FAMILY",
    desc: "精選親子互動、收藏與設計選品，適合家庭日常與節慶贈禮。",
  },
} as const;

export const audienceGroups = [
  {
    title: "送給重視保養的她",
    en: "FOR THE NURTURED",
    brands: ["LASAI", "Panier des Sens 潘提香頌", "聖朵波緹", "茶寶", "覺萃"],
  },
  {
    title: "送給喜愛香氛的她",
    en: "FOR THE FRAGRANT",
    brands: ["J-scent", "EcoScential", "美珂媞歐", "郁郁"],
  },
  {
    title: "送給喜歡茶酒的她",
    en: "FOR THE CONNOISSEUR",
    brands: ["蒔年一晌", "覓梅酒", "沃堤思世界茶莊園"],
  },
  {
    title: "送給家庭與親子",
    en: "FOR THE FAMILY",
    brands: ["MAGBLOX", "SONNY ANGEL", "黑白小姐"],
  },
];
